# 1. Project Identification
sonar.projectKey=elevate-flutter-team_GitHub-Actions-C4
sonar.organization=elevate-flutter-team

# 2. Source Code
sonar.sources=lib, pubspec.yaml
sonar.tests=test
sonar.sourceEncoding=UTF-8

# 3. Flutter Coverage Path
sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.branch.name=main